spring.application.name=file-processor
management.endpoints.web.exposure.include=health,info,prometheus
management.metrics.tags.application=file-processor-api

spring.jpa.properties.hibernate.validator.apply_to_ddl=false

spring.datasource.url=jdbc:postgresql://localhost:5432/file_processor_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=true

spring.jpa.hibernate.ddl-auto=update
spring.flyway.enabled=false

spring.cloud.aws.credentials.access-key=test
spring.cloud.aws.credentials.secret-key=test
spring.cloud.aws.region.static=us-east-1

spring.cloud.aws.s3.endpoint=http://localhost:4566
spring.cloud.aws.sqs.endpoint=http://localhost:4566
spring.cloud.aws.sqs.listener.queue-not-found-strategy=CREATE

spring.cloud.aws.s3.path-style-access-enabled=true
